language: java
jdk:
  - oraclejdk8

install:
  - mvn install -Dgpg.skip=true

script:
  - mvn test

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: always